### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by aquynh** [Becojo/asmbot#1]
cool, is this a bot for Slack? will you have a README in the future?
some screenshots would be awesome, too!

keep it up, cheers!

**Comment by becojo** [comment]
Funny how you found this so quickly haha.

I made this at REcon last year (probably during your talk) and didn't bother updating/publishing it. I will update soon to include more infos!

Here's a screenshot

![](http://i.imgur.com/XBs28yi.png)

**Comment by aquynh** [comment]
oh cool, did we talk in person at RECON last year?

thanks for the fantastic screenshot! linked to your tool now from our websites: http://www.capstone-engine.org/showcase.html & http://www.keystone-engine.org/showcase/

cheers!

**Comment by aquynh** [comment]
will you add README to this? still looking forward to it
